# .github/workflows/build.yml

# Build
name: "Build for all branches making a PR"

on:
    pull_request:
        branches:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Set node version
              uses: actions/setup-node@v2
              with:
                  node-version: 18.17.1
            - name: Install dependencies
              run: yarn
            - name: Build Vite
              run: yarn build
            - name: Build Storybook
              run: yarn build-storybook
              
