# .github/workflows/test.yml

# Test
name: "Test for all branches making a PR"

on:
  pull_request:
      branches:
          - "*"

jobs:
    build-test:
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Set node version
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: yarn
            - name: Install Playwright
              run: npx playwright install --with-deps
            - name: Build Storybook
              run: yarn build-storybook --quiet
            - name: Serve Storybook and run tests
              run: |
                npx concurrently -k -s first -n "SB,TEST" \
                  "npx http-server storybook-static --port 6006 --silent" \
                  "npx wait-on tcp:127.0.0.1:6006 && yarn test-storybook"
